### ISSUE TITLE
Publish this resource as docker-image

### ISSUE THREAD

**Issue by o-orand** [pivotal-cf-experimental/cron-resource#1]
To be able to easily use this resource on any concourse using a [resource_type](https://concourse.ci/configuring-resource-types.html), it could be nice to have it published as a docker image. Tentative seems to exist on [cron-resource@dockerhub](https://hub.docker.com/r/cftoolsmiths/cron-resource/).

I've done something here [cron-resource-builder](https://github.com/Orange-OpenSource/cron-resource-builder/), if you want to reuse it.

**Comment by derwei** [comment]
@o-orand We fixed the 'automated build' for our cron-resource on Dockerhub. We have some teams that is already using this as a docker image on their Concourse workers. Please let us know if you'd like us to add anything else.

https://hub.docker.com/r/cftoolsmiths/cron-resource/
